<!doctype html>
    <html lang="en-gb" dir="ltr" class="uk-notouch">
        <head>
        	<meta charset="utf-8">
            <?php header('X-UA-Compatible: IE=edge,chrome=1');//taming IE ?>
        	<meta name="viewport" content="width=device-width, initial-scale=1.0">
        	<title><?php echo $page->title;?></title>
            <link rel="stylesheet" href="<?php echo $config->urls->templates;?>sass/app.css" />
        </head>
    </html>
